export function gpuTimer(device){
 const create=device.createCommandEncoder.bind(device);let active=null;
 const slots=Array.from({length:3},()=>({busy:false,query:device.createQuerySet({label:'bench:timestamps',type:'timestamp',count:512}),resolve:device.createBuffer({label:'bench:resolve',size:4096,usage:GPUBufferUsage.QUERY_RESOLVE|GPUBufferUsage.COPY_SRC}),read:device.createBuffer({label:'bench:read',size:4096,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ})}));
 const timer={stage:null,start(row){const slot=slots.find(s=>!s.busy);if(!slot)throw Error('Timestamp ring overflow');Object.assign(slot,{busy:true,used:0,passes:[],row});active=slot;},finish(){const slot=active;active=null;if(!slot.used){slot.busy=false;throw Error('No GPU passes rendered');}const e=create({label:'bench:resolve'});e.resolveQuerySet(slot.query,0,slot.used,slot.resolve,0);e.copyBufferToBuffer(slot.resolve,0,slot.read,0,slot.used*8);device.queue.submit([e.finish()]);slot.promise=slot.read.mapAsync(GPUMapMode.READ,0,slot.used*8).then(()=>{const t=new BigUint64Array(slot.read.getMappedRange(0,slot.used*8));const passes=slot.passes.map(p=>({...p,start:Number(t[p.begin]),end:Number(t[p.end]),ms:Number(t[p.end]-t[p.begin])/1e6}));slot.row.passes=passes;slot.row.gpuMs=(Math.max(...passes.map(p=>p.end))-Math.min(...passes.map(p=>p.start)))/1e6;slot.row.gpuPassSumMs=passes.reduce((n,p)=>n+p.ms,0);slot.row.gpuComputeMs=passes.filter(p=>p.kind==='compute').reduce((n,p)=>n+p.ms,0);slot.row.gpuSortMs=passes.filter(p=>p.stage==='sort').reduce((n,p)=>n+p.ms,0);slot.row.gpuRenderMs=passes.filter(p=>p.kind==='render').reduce((n,p)=>n+p.ms,0);slot.read.unmap();}).finally(()=>{slot.busy=false;});return slot.promise;},async drain(){await Promise.all(slots.filter(s=>s.busy).map(s=>s.promise));}};
 device.createCommandEncoder=(...args)=>{const encoder=create(...args);for(const [name,kind] of [['beginComputePass','compute'],['beginRenderPass','render']]){const original=encoder[name].bind(encoder);encoder[name]=(descriptor={})=>{if(!active)return original(descriptor);if(active.used+2>512)throw Error('Too many timestamp passes');const pass={kind,stage:timer.stage,begin:active.used++,end:active.used++,label:descriptor.label||'',pipelines:[]};active.passes.push(pass);const p=original({...descriptor,timestampWrites:{querySet:active.query,beginningOfPassWriteIndex:pass.begin,endOfPassWriteIndex:pass.end}});const set=p.setPipeline.bind(p);p.setPipeline=(pipeline)=>{if(pipeline.label&&!pass.pipelines.includes(pipeline.label))pass.pipelines.push(pipeline.label);return set(pipeline);};return p;};}return encoder;};
 return timer;
}
export const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export async function fenceGL(gl){const f=gl.fenceSync(gl.SYNC_GPU_COMMANDS_COMPLETE,0);gl.flush();while(true){const s=gl.clientWaitSync(f,0,0);if(s===gl.WAIT_FAILED)throw Error('WebGL fence failed');if(s!==gl.TIMEOUT_EXPIRED)break;await sleep(0);}gl.deleteSync(f);}
